"""Franka Emika Panda asset configuration for mjlab.

Mirrors the pattern of ``mjlab.asset_zoo.robots.i2rt_yam.yam_constants``: the
upstream Menagerie XML is loaded via ``mujoco.MjSpec``, the XML-defined
actuators and keyframes are stripped, and mjlab's own
``BuiltinPositionActuatorCfg`` / ``InitialStateCfg`` are layered on top.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

import mujoco

if TYPE_CHECKING:
    import numpy as np

from mjlab.actuator import BuiltinPositionActuatorCfg
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg

##
# MJCF and assets.
##

FRANKA_XML: Path = Path(__file__).resolve().parent / "xmls" / "panda_nohand.xml"
assert FRANKA_XML.exists(), (
    f"{FRANKA_XML} missing. Run `uv run python scripts/fetch_franka.py` first."
)

FRANKA_ENTITY_NAME = "robot"
# Site name in panda_nohand.xml, located at the standard hand attachment
# frame (0.107 m along link7 z-axis). Used as the end-effector reference.
EE_SITE_NAME = "attachment_site"

ARM_JOINT_NAMES = tuple(f"joint{i}" for i in range(1, 8))


def _strip_xml_actuators_and_keyframes(spec: mujoco.MjSpec) -> mujoco.MjSpec:
    """Remove XML-defined actuators and keyframes so mjlab's configs win."""
    for actuator in list(spec.actuators):
        spec.delete(actuator)
    for key in list(spec.keys):
        spec.delete(key)
    return spec


def get_spec() -> mujoco.MjSpec:
    """Build a clean Franka MjSpec ready for mjlab to attach actuators to."""
    spec = mujoco.MjSpec.from_file(str(FRANKA_XML))
    return _strip_xml_actuators_and_keyframes(spec)


##
# Actuator config.
##

# PD gains roughly matching the Menagerie default <general> actuators
# (gainprm/biasprm), tuned for stable position control at 50-100 Hz.
# joints 1-4 use the stronger motors, joints 5-7 the wrist motors.
_STIFFNESS = {
    "joint1": 1000.0,
    "joint2": 1000.0,
    "joint3": 750.0,
    "joint4": 750.0,
    "joint5": 300.0,
    "joint6": 300.0,
    "joint7": 300.0,
}
_DAMPING = {
    "joint1": 20.0,
    "joint2": 20.0,
    "joint3": 4.0,
    "joint4": 4.0,
    "joint5": 2.0,
    "joint6": 2.0,
    "joint7": 2.0,
}
_EFFORT_LIMIT = {
    "joint1": 87.0,
    "joint2": 87.0,
    "joint3": 87.0,
    "joint4": 87.0,
    "joint5": 12.0,
    "joint6": 12.0,
    "joint7": 12.0,
}
_ARMATURE = 0.1  # matches the XML default joint armature


ARM_ACTUATORS: tuple[BuiltinPositionActuatorCfg, ...] = tuple(
    BuiltinPositionActuatorCfg(
        target_names_expr=(name,),
        stiffness=_STIFFNESS[name],
        damping=_DAMPING[name],
        effort_limit=_EFFORT_LIMIT[name],
        armature=_ARMATURE,
    )
    for name in ARM_JOINT_NAMES
)

ARTICULATION = EntityArticulationInfoCfg(
    actuators=ARM_ACTUATORS,
    soft_joint_pos_limit_factor=0.95,
)

##
# Keyframe config.
##

# "Home" pose from the Menagerie keyframe (qpos for the 7 arm joints).
HOME_KEYFRAME = EntityCfg.InitialStateCfg(
    joint_pos={
        "joint1": 0.0,
        "joint2": 0.0,
        "joint3": 0.0,
        "joint4": -math.pi / 2,
        "joint5": 0.0,
        "joint6": math.pi / 2,
        "joint7": -math.pi / 4,
    },
    joint_vel={".*": 0.0},
)


def get_franka_robot_cfg() -> EntityCfg:
    """Build the Franka Panda (no hand) EntityCfg."""
    return EntityCfg(
        init_state=HOME_KEYFRAME,
        spec_fn=get_spec,
        articulation=ARTICULATION,
    )


# Action scale per joint (0.25 * effort_limit / stiffness), matching the
# convention used by ``G1_ACTION_SCALE`` and ``YAM_ACTION_SCALE`` in mjlab.
FRANKA_ACTION_SCALE: dict[str, float] = {
    name: 0.25 * _EFFORT_LIMIT[name] / _STIFFNESS[name] for name in ARM_JOINT_NAMES
}


##
# EE workspace convex hull (generated by scripts/map_ee_workspace.py).
##

EE_WORKSPACE_PATH: Path = Path(__file__).resolve().parent / "ee_workspace.npz"


def load_ee_workspace() -> dict[str, "np.ndarray"]:
    """Load the pre-computed EE workspace convex hull.

    Returns a dict with keys:
        - ``vertices``: (V, 3) hull vertex positions
        - ``equations``: (F, 4) half-plane equations (normal | offset)
    """
    import numpy as np

    if not EE_WORKSPACE_PATH.exists():
        raise FileNotFoundError(
            f"{EE_WORKSPACE_PATH} not found. "
            "Run `uv run python scripts/map_ee_workspace.py` first."
        )
    data = np.load(EE_WORKSPACE_PATH)
    return {"vertices": data["vertices"], "equations": data["equations"]}


def is_inside_workspace(points: "np.ndarray", equations: "np.ndarray") -> "np.ndarray":
    """Test whether points lie inside the EE workspace convex hull.

    Args:
        points: (..., 3) array of 3D positions.
        equations: (F, 4) half-plane equations from :func:`load_ee_workspace`.

    Returns:
        Boolean array of shape ``points.shape[:-1]``. True if inside.
    """
    import numpy as np

    # Half-plane test: point p is inside iff  equations[:, :3] @ p + equations[:, 3] <= 0
    # for ALL faces.
    normals = equations[:, :3]  # (F, 3)
    offsets = equations[:, 3]  # (F,)
    # points: (..., 3) → dots: (..., F)
    dots = np.einsum("...j,fj->...f", points, normals) + offsets
    return np.all(dots <= 0, axis=-1)


if __name__ == "__main__":
    import mujoco.viewer as viewer

    from mjlab.entity.entity import Entity

    robot = Entity(get_franka_robot_cfg())
    viewer.launch(robot.spec.compile())
