"""Franka Emika Panda asset configuration for mjlab.

Supports both the arm-only (panda_nohand.xml) and full arm+gripper (panda.xml)
configurations, defaulting to the no-gripper version.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

import mujoco

if TYPE_CHECKING:
    import numpy as np

from mjlab.actuator import BuiltinPositionActuatorCfg
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg

##
# MJCF and assets.
##

XML_DIR = Path(__file__).resolve().parent / "xmls"
FRANKA_NOHAND_XML: Path = XML_DIR / "panda_nohand.xml"
FRANKA_WITH_HAND_XML: Path = XML_DIR / "panda.xml"

for xml_path in (FRANKA_NOHAND_XML, FRANKA_WITH_HAND_XML):
    assert xml_path.exists(), (
        f"{xml_path} missing. Run `uv run python scripts/fetch_franka.py` first."
    )

FRANKA_ENTITY_NAME = "robot"
# Default site name (can vary depending on XML, but attachment_site is standard)
EE_SITE_NAME = "attachment_site"

ARM_JOINT_NAMES = tuple(f"joint{i}" for i in range(1, 8))
GRIPPER_JOINT_NAMES = ("finger_joint1", "finger_joint2")


def _strip_xml_actuators_and_keyframes(spec: mujoco.MjSpec) -> mujoco.MjSpec:
    """Remove XML-defined actuators and keyframes so mjlab's configs win."""
    for actuator in list(spec.actuators):
        spec.delete(actuator)
    for key in list(spec.keys):
        spec.delete(key)
    return spec


def get_spec(with_gripper: bool = False) -> mujoco.MjSpec:
    """Build a clean Franka MjSpec ready for mjlab to attach actuators to."""
    xml_path = FRANKA_WITH_HAND_XML if with_gripper else FRANKA_NOHAND_XML
    spec = mujoco.MjSpec.from_file(str(xml_path))
    return _strip_xml_actuators_and_keyframes(spec)


##
# Actuator config.
##

_STIFFNESS = {
    "joint1": 1000.0,
    "joint2": 1000.0,
    "joint3": 750.0,
    "joint4": 750.0,
    "joint5": 300.0,
    "joint6": 300.0,
    "joint7": 300.0,
    "finger_joint1": 100.0,
    "finger_joint2": 100.0,
}
_DAMPING = {
    "joint1": 20.0,
    "joint2": 20.0,
    "joint3": 4.0,
    "joint4": 4.0,
    "joint5": 2.0,
    "joint6": 2.0,
    "joint7": 2.0,
    "finger_joint1": 10.0,
    "finger_joint2": 10.0,
}
_EFFORT_LIMIT = {
    "joint1": 87.0,
    "joint2": 87.0,
    "joint3": 87.0,
    "joint4": 87.0,
    "joint5": 12.0,
    "joint6": 12.0,
    "joint7": 12.0,
    "finger_joint1": 20.0,
    "finger_joint2": 20.0,
}
_ARMATURE = 0.1

ARM_ACTUATORS: tuple[BuiltinPositionActuatorCfg, ...] = tuple(
    BuiltinPositionActuatorCfg(
        target_names_expr=(name,),
        stiffness=_STIFFNESS[name],
        damping=_DAMPING[name],
        effort_limit=_EFFORT_LIMIT[name],
        armature=_ARMATURE,
    )
    for name in ARM_JOINT_NAMES
)

GRIPPER_ACTUATORS: tuple[BuiltinPositionActuatorCfg, ...] = tuple(
    BuiltinPositionActuatorCfg(
        target_names_expr=(name,),
        stiffness=_STIFFNESS[name],
        damping=_DAMPING[name],
        effort_limit=_EFFORT_LIMIT[name],
        armature=_ARMATURE,
    )
    for name in GRIPPER_JOINT_NAMES
)


def get_articulation_cfg(with_gripper: bool = False) -> EntityArticulationInfoCfg:
    """Get articulation config containing arm and optionally gripper actuators."""
    actuators = ARM_ACTUATORS + GRIPPER_ACTUATORS if with_gripper else ARM_ACTUATORS
    return EntityArticulationInfoCfg(
        actuators=actuators,
        soft_joint_pos_limit_factor=0.95,
    )


##
# Keyframe config.
##

def get_home_keyframe(with_gripper: bool = False) -> EntityCfg.InitialStateCfg:
    """Get home keyframe joint positions including gripper states if requested."""
    joint_pos = {
        "joint1": 0.0,
        "joint2": 0.0,
        "joint3": 0.0,
        "joint4": -math.pi / 2,
        "joint5": 0.0,
        "joint6": math.pi / 2,
        "joint7": -math.pi / 4,
    }
    if with_gripper:
        # Fully open or partially open default position for Panda fingers
        joint_pos.update({
            "finger_joint1": 0.04,
            "finger_joint2": 0.04,
        })
        
    return EntityCfg.InitialStateCfg(
        joint_pos=joint_pos,
        joint_vel={".*": 0.0},
    )


def get_franka_robot_cfg(with_gripper: bool = False) -> EntityCfg:
    """Build the Franka Panda EntityCfg, defaulting to no gripper."""
    return EntityCfg(
        init_state=get_home_keyframe(with_gripper),
        spec_fn=lambda: get_spec(with_gripper),
        articulation=get_articulation_cfg(with_gripper),
    )


# Action scale per joint dictionary encompassing both arm and gripper
FRANKA_ACTION_SCALE: dict[str, float] = {
    name: 0.25 * _EFFORT_LIMIT[name] / _STIFFNESS[name] 
    for name in (*ARM_JOINT_NAMES, *GRIPPER_JOINT_NAMES)
}


##
# EE workspace convex hull (generated by scripts/map_ee_workspace.py).
##

EE_WORKSPACE_PATH: Path = Path(__file__).resolve().parent / "ee_workspace.npz"


def load_ee_workspace() -> dict[str, "np.ndarray"]:
    """Load the pre-computed EE workspace convex hull."""
    import numpy as np

    if not EE_WORKSPACE_PATH.exists():
        raise FileNotFoundError(
            f"{EE_WORKSPACE_PATH} not found. "
            "Run `uv run python scripts/map_ee_workspace.py` first."
        )
    data = np.load(EE_WORKSPACE_PATH)
    return {"vertices": data["vertices"], "equations": data["equations"]}


def is_inside_workspace(points: "np.ndarray", equations: "np.ndarray") -> "np.ndarray":
    """Test whether points lie inside the EE workspace convex hull."""
    import numpy as np

    normals = equations[:, :3]
    offsets = equations[:, 3]
    dots = np.einsum("...j,fj->...f", points, normals) + offsets
    return np.all(dots <= 0, axis=-1)


if __name__ == "__main__":
    import mujoco.viewer as viewer

    from mjlab.entity.entity import Entity

    # Defaults to no gripper unless passed True
    robot = Entity(get_franka_robot_cfg(with_gripper=False))
    viewer.launch(robot.spec.compile())